### ISSUE TITLE
Make it Runtime Agnostic

### ISSUE THREAD

**Issue by ahmedrowaihi** [tawashy/urway.js#10]
## Problem
This module works only for NodeJs Runtime
The reason is that we use the ```crypto``` module which is a native NodeJs module and it's also deprecated 
![image](https://user-images.githubusercontent.com/67356781/214442574-19e89b30-bc27-473c-b5cf-de8e8c402dc3.png)

## Solution
To support other runtimes we can use [crypto-js](https://www.npmjs.com/package/crypto-js) 
which is also used in [urway-appleapy-react-native](https://github.com/URWAYios/urway-appleapy-react-native/blob/e9aa6bf2ec35deee07d8f600274b54d0aa9cd81c/src/index.js#L3)
 
Assign me for this task if you guys agree on this.

**Comment by tawashy** [comment]
Great! I've created a branch and assigned the task to you @ahmedrowaihi  😃

**Comment by ahmedrowaihi** [comment]
Niceeee now it will work on REACT NATIVE AS WELL
